
project:
  type: book
  output-dir: _book

book:
  title: "Introdução à Computação Aplicada às Ciências Atmosféricas"
  author: "Curso de Meteorologia - UEMA, Profa. Dra. Izadora S. de Carvalho"
  cover-image: cover_meteo300dpi.png
  favicon: cover_meteo300dpi.png
  reader-mode: true
  repo-url: https://github.com/IzadoraSC/ebook-intro-computacao-meteorologia
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    #- capitulos/00-cronograma.qmd
    - index.qmd
    - capitulos/cap1-introducao.qmd
    - capitulos/cap2-fundamentos-programacao.qmd
    - capitulos/cap3-estruturas-dados.qmd
    - capitulos/cap4-manipulacao-dados.qmd
    - capitulos/cap5-dados_vetoriais.qmd
    - capitulos/cap6-exercicios-fixacao.qmd
    - capitulos/cap7-fundamentos-python.qmd
    
lang: pt    

format:
  html:
    theme: cosmo
    css: styles.css
    code-link: true
    callout-appearance: simple
  # pdf:
  #   documentclass: scrreprt

editor: visual